version: "3.9" # optional sinece v1.27.0
services:
  py3:
    build:
      context: ./py3
      dockerfile: Dockerfile
    working_dir: /workspace
    entrypoint: ["python", "app.py"]
    volumes:
      # Workspace
      - ./workspace:/workspace
      # WSLg
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      # WSLg
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
      # GPUを使うための設定
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    # GPUを使うための設定
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
